### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yuta0801** [dischanet/issues-discord-bot#7]
- [x] DONE promise+async/await+catch
- [x] DONE [a-zA-Z0-9]{8} -> \d+
- [ ] 変数名を変更 msg -> args
- [ ] common-tagsで複数行テンプレートリテラルのインデント揃える(stripIndent)
- [ ] 引数を分割代入
- [ ] moment.jsを使って日時をフォーマットする
- [ ] 正規表現で非キャプチャリング括弧を使う
- [ ] ユーザータグではなくIDで比較する
- [ ] 一覧にもっと情報の乗せる
- [ ] IDの前に＃をつける
- [ ] 引数が不正なときにメッセージを送る

- [ ] コマンド判定を改善する addCommand -> Object, Map
- [ ] コマンドのクラス化
- [ ] ロードシステム
